name: Price Checker Cron

on:
  schedule:
    - cron: "0 * * * *"   # запуск щогодини (UTC час)
  workflow_dispatch:       # дозволяє вручну запускати з GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price_checker
        run: python price_checker.py
